# -*- coding: utf-8 -*-
"""Ch7matplotlibLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10xWPfagzc1Usj_IGyrxZgtJ1S1jiXSaU
"""

import matplotlib.pyplot as plt

heights = [100, 200, 300, 400, 500]
left_edges = [0, 1, 2, 3, 4]
plt.bar(left_edges,heights,color=('r', 'g', 'b', 'w', 'k'))
plt.title('Sales by Year')
plt.xlabel('Year')
plt.ylabel('Sales')
plt.xticks([0.5, 1.5, 2.5, 3.5, 4.5],
['2016', '2017', '2018', '2019', '2020'])
plt.yticks([0, 100, 200, 300, 400, 500],
['$0m', '$1m', '$2m', '$3m', '$4m', '$5m'])

plt.show()