# -*- coding: utf-8 -*-
"""ExerciseChap7ListLK

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rEjcpyuAToWUjBTgtnNBsiT-xLkQT-sx
"""

#First Method

scores =[2.5, 7.3, 6.5, 4.0, 5.2]
j = 0
for i in scores:
  j = j + i
avg = j/len(scores)
print(f"The average of the elements is {avg:.2f}")

#Second Method

def Average(List):
  avg = sum(List)/len(List)
  print(f"The average of the elements is {avg:.2f}")

Average(scores)

def main():
  infile = open("city.txt","w")
  infile.write('New York\n')
  infile.write('Boston\n')
  infile.write('Atlanta\n')
  infile.write('Dallas\n')
  infile.close()

if __name__ == "__main__":
  main()

def main1(filename):
  List = []
  try:
      with open(filename,"r") as file:
        for line in file:
          try:
              city = line.strip()
              List.append(city)
          except ValueError:
                print(f"Skipping invalid value: {line.strip()}")
  except FileNotFoundError:
        print(f"File {filename} not found.")
        raise
  return List

main1("city.txt")